### PR TITLE
feat(#58): Add exclude pattern support

### PR DESCRIPTION
**Pull request by spencer-shupe-qhr**
https://github.com/allegro/typescript-strict-plugin/issues/58

Config has been extended to include `excludePattern` which uses https://github.com/isaacs/minimatch for glob pattern matching.

### CODE REVIEW

**Comment by spencer-shupe-qhr** [comment]
Merging or feedback on this PR would be greatly appreciated!

**Comment by KostkaBrukowa** [comment]
Hey!! Great job! I've tested it and the solution looks very clean. If you fix lint and merge conflicts I'll be happy to merge and release it!

**Comment by spencer-shupe-qhr** [comment]
I've updated jest and ts-jest dependencies and re-built the package-lock in order to avoid installing with --force or --legacy-peer-deps. Let me know if you have a different preference or idea wrt how to avoid the peer conflicts. Thanks for maintaining this project!

**Review by KostkaBrukowa — APPROVED** [review]

**Comment by KostkaBrukowa** [comment]
Published with `2.4.0` Thanks for contribution!!

**Pull request merged**
